In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:1:2])

[1]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-1:2])

[1 3 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:2])

[1 2]


In [9]:
import numpy as np
d = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[11, 12, 13, 14, 15],[16,17,18,19,20]]])
d[0:2,1,1:4]


array([[ 7,  8,  9],
       [17, 18, 19]])

In [2]:
import numpy as np
d = np.array([[[45,67,89,23],[6,7,8,9]],[[19, 52, 13, 19],[34,90,45,19]]])
d[1]

array([[19, 52, 13, 19],
       [34, 90, 45, 19]])

In [3]:
import numpy as np
d = np.array([[[45,67,89,23],[6,7,8,9]],[[19, 52, 13, 19],[34,90,45,19]]])
d[0]

array([[45, 67, 89, 23],
       [ 6,  7,  8,  9]])

In [8]:
import numpy as np
d = np.array([[[45,67,89,23],[6,7,8,9]],[[19, 52, 13, 19],[34,90,45,19]]])
d[:2]

array([[[45, 67, 89, 23],
        [ 6,  7,  8,  9]],

       [[19, 52, 13, 19],
        [34, 90, 45, 19]]])